# 
# File Generated by GEOS buildExec 
# Copyright (c) 2023 DefinitelyNotAGirl@github 
#
include MAKE/modules.mak
include MAKE/FUNCDIS.module.mak
include MAKE/INIT.module.mak
include MAKE/klib.module.mak
